#! /bin/bash
set -eux

sudo apt-get install tk-dev libssl-dev libsqlite3-dev \
liblzma-dev libreadline-dev libbz2-dev libffi-dev \
curl

curl https://pyenv.run | bash

pyenv install 3.11

pyenv --global 3.11
